import { EventData } from '../interfaces/common.interface';

export const featuredEvent: EventData = {
     id: 1,
     title: 'Google I/O 2025',
     date: '2025-05-20',
     location: 'Online',
     description: 'Join us for live streamed keynotes, sessions, and more.',
     hashtag: '#GoogleIO',
     image: 'https://developers.google.com/static/events/images/io25_720.png',
     product: 'Multi-product',
     scope: 'Global',
     category: 'Tech',
     tags: ['Innovation', 'Keynote'],
     popularity: 100,
     status: '',
     countdown: undefined
};

export const upcomingEvents: EventData[] = [
     {
          id: 2,
          title: 'Google I/O Connect Berlin',
          date: '2025-06-25',
          location: 'Berlin | In-person',
          description: 'Experience the magic of Google I/O Connect in Berlin! Dive into interactive sessions, experience demos, and connect with fellow developers.',
          hashtag: '#GoogleIOConnect',
          image: 'https://developers.google.com/static/focus/images/berlin_720.png',
          product: 'Multi-product',
          scope: 'Global',
          category: 'Tech',
          tags: ['Networking', 'Demos'],
          popularity: 80,
          status: '',
          countdown: undefined
     },
     {
          id: 3,
          title: 'DevFest Stockholm',
          date: '2025-07-10',
          location: 'Stockholm | In-person',
          description: 'Join the vibrant developer community at DevFest Stockholm for workshops and networking.',
          hashtag: '#DevFest',
          image: 'https://developers.google.com/static/focus/images/berlin_720.png',
          product: 'Multi-product',
          scope: 'Global',
          category: 'Tech',
          tags: ['Workshops', 'Community'],
          popularity: 70,
          status: '',
          countdown: undefined
     },
     {
          id: 4,
          title: 'AI Summit London',
          date: '2025-08-05',
          location: 'London | Hybrid',
          description: 'Explore the future of AI with hands-on labs and expert talks. olm for workshops and networking.',
          hashtag: '#AISummit',
          image: 'https://developers.google.com/static/focus/images/berlin_720.png',
          product: 'AI',
          scope: 'Global',
          category: 'AI',
          tags: ['AI', 'Labs'],
          popularity: 90,
          status: '',
          countdown: undefined
     }
];

export const recentEvents: EventData[] = [
     {
          id: 1,
          title: 'Google Cloud x MLB Hackathon',
          date: '2024-12-13',
          location: 'Global',
          description: 'Join the hackathon to innovate with Google Cloud and MLB.',
          hashtag: '#GoogleCloud',
          image: 'https://developers.google.com/static/focus/images/berlin_720.png',
          product: 'Google Cloud',
          scope: 'Global',
          category: 'Tech',
          tags: ['Hackathon', 'Cloud'],
          popularity: 75,
          status: '',
          countdown: undefined
     },
     {
          id: 2,
          title: 'AWS Summit 2024',
          date: '2024-06-15',
          location: 'New York, USA',
          description: 'Explore the latest innovations in cloud computing at AWS Summit.',
          hashtag: '#AWSSummit',
          image: 'https://aws.amazon.com/summits/images/summit2024.jpg',
          product: 'AWS',
          scope: 'Regional',
          category: 'Tech',
          tags: ['Cloud', 'Summit'],
          popularity: 85,
          status: '',
          countdown: undefined
     },
     {
          id: 3,
          title: 'React Conf 2024',
          date: '2024-09-10',
          location: 'San Francisco, USA',
          description: 'The biggest React conference, full of insights from the React community.',
          hashtag: '#ReactConf',
          image: 'https://reactjs.org/static/react-logo.90bce52e.png',
          product: 'React',
          scope: 'National',
          category: 'Tech',
          tags: ['Conference', 'React'],
          popularity: 90,
          status: '',
          countdown: undefined
     },
     {
          id: 4,
          title: 'Microsoft Build 2024',
          date: '2024-05-18',
          location: 'Seattle, USA',
          description: 'The annual developer event for Microsoft technologies.',
          hashtag: '#MicrosoftBuild',
          image: 'https://developer.microsoft.com/assets/images/build-logo.svg',
          product: 'Microsoft',
          scope: 'Global',
          category: 'Tech',
          tags: ['Developer', 'Conference'],
          popularity: 88,
          status: '',
          countdown: undefined
     },
     {
          id: 5,
          title: 'DevOps World 2024',
          date: '2024-07-22',
          location: 'London, UK',
          description: 'Join the DevOps community to discuss the latest in DevOps technologies.',
          hashtag: '#DevOpsWorld',
          image: 'https://www.cloudbees.com/hubfs/DevOps-World-2021.png',
          product: 'DevOps',
          scope: 'Regional',
          category: 'Tech',
          tags: ['DevOps', 'Conference'],
          popularity: 70,
          status: '',
          countdown: undefined
     },
     {
          id: 6,
          title: 'Apple WWDC 2024',
          date: '2024-06-05',
          location: 'Cupertino, USA',
          description: 'Apple’s annual developer conference showcasing new software updates.',
          hashtag: '#WWDC2024',
          image: 'https://developer.apple.com/assets/elements/icons/wwdc/wwdc-logos/WWDC-Logo-2024.svg',
          product: 'Apple',
          scope: 'Global',
          category: 'Tech',
          tags: ['Conference', 'Apple'],
          popularity: 95,
          status: '',
          countdown: undefined
     },
     {
          id: 8,
          title: 'Google I/O 2024',
          date: '2024-05-12',
          location: 'Mountain View, USA',
          description: 'Join Google’s developers for the latest in tech innovations.',
          hashtag: '#GoogleIO',
          image: 'https://developers.google.com/static/io/images/google-io-logo.svg',
          product: 'Google',
          scope: 'Global',
          category: 'Tech',
          tags: ['Conference', 'Google'],
          popularity: 92,
          status: '',
          countdown: undefined
     },
     {
          id: 9,
          title: 'PyCon 2024',
          date: '2024-04-26',
          location: 'Salt Lake City, USA',
          description: 'The largest gathering of Python enthusiasts in the world.',
          hashtag: '#PyCon',
          image: 'https://www.pycon.org/images/pycon-logo.svg',
          product: 'Python',
          scope: 'National',
          category: 'Tech',
          tags: ['Conference', 'Python'],
          popularity: 80,
          status: '',
          countdown: undefined
     },
     {
          id: 10,
          title: 'DockerCon 2024',
          date: '2024-06-22',
          location: 'San Francisco, USA',
          description: 'Learn about containerization and Docker at DockerCon.',
          hashtag: '#DockerCon',
          image: 'https://www.docker.com/sites/default/files/d8/2019-04/dockercon-2019-hero-3x.png',
          product: 'Docker',
          scope: 'Regional',
          category: 'Tech',
          tags: ['Docker', 'Conference'],
          popularity: 77,
          status: '',
          countdown: undefined
     },
     {
          id: 11,
          title: 'KubeCon + CloudNativeCon 2024',
          date: '2024-08-11',
          location: 'Berlin, Germany',
          description: 'Join Kubernetes and Cloud Native enthusiasts for the largest gathering.',
          hashtag: '#KubeCon',
          image: 'https://www.cncf.io/wp-content/uploads/2024/01/KubeCon-logo-2024.png',
          product: 'Kubernetes',
          scope: 'Global',
          category: 'Tech',
          tags: ['Kubernetes', 'Cloud Native'],
          popularity: 85,
          status: '',
          countdown: undefined
     },
     {
          id: 12,
          title: 'AWS re:Invent 2024',
          date: '2024-11-28',
          location: 'Las Vegas, USA',
          description: 'Learn the latest in AWS technologies at re:Invent.',
          hashtag: '#AWSreinvent',
          image: 'https://d1.awsstatic.com/reinvent/2024/awsreinvent2024-logo.60f7ff64b7a9c4b818831e7b47c6cc7b4e92d8f4.png',
          product: 'AWS',
          scope: 'Global',
          category: 'Tech',
          tags: ['AWS', 'Conference'],
          popularity: 95,
          status: '',
          countdown: undefined
     },
     {
          id: 13,
          title: 'Salesforce Dreamforce 2024',
          date: '2024-09-15',
          location: 'San Francisco, USA',
          description: 'Salesforce’s premier event for innovators and business leaders.',
          hashtag: '#Dreamforce',
          image: 'https://www.salesforce.com/blog/wp-content/uploads/2023/12/dreamforce-logo.svg',
          product: 'Salesforce',
          scope: 'Global',
          category: 'Business',
          tags: ['Salesforce', 'Business'],
          popularity: 90,
          status: '',
          countdown: undefined
     },
     {
          id: 14,
          title: 'Cybersecurity Summit 2024',
          date: '2024-10-20',
          location: 'Chicago, USA',
          description: 'Leading cybersecurity experts discuss trends and innovations.',
          hashtag: '#CyberSecuritySummit',
          image: 'https://example.com/images/cybersecurity.jpg',
          product: 'Cybersecurity',
          scope: 'National',
          category: 'Security',
          tags: ['Cybersecurity', 'Summit'],
          popularity: 78,
          status: '',
          countdown: undefined
     },
     {
          id: 15,
          title: 'Blockchain Summit 2024',
          date: '2024-07-15',
          location: 'Singapore',
          description: 'Dive deep into blockchain technology and its applications.',
          hashtag: '#BlockchainSummit',
          image: 'https://example.com/images/blockchain.jpg',
          product: 'Blockchain',
          scope: 'International',
          category: 'Tech',
          tags: ['Blockchain', 'Summit'],
          popularity: 82,
          status: '',
          countdown: undefined
     },
     {
          id: 16,
          title: 'AI Expo 2024',
          date: '2024-06-08',
          location: 'Los Angeles, USA',
          description: 'Explore the world of artificial intelligence and its future.',
          hashtag: '#AIExpo',
          image: 'https://example.com/images/ai_expo.jpg',
          product: 'AI',
          scope: 'National',
          category: 'Tech',
          tags: ['AI', 'Conference'],
          popularity: 85,
          status: '',
          countdown: undefined
     },
     {
          id: 17,
          title: 'TechCrunch Disrupt 2024',
          date: '2024-09-25',
          location: 'San Francisco, USA',
          description: 'TechCrunch’s annual event showcasing the latest startups.',
          hashtag: '#TechCrunchDisrupt',
          image: 'https://example.com/images/techcrunch.jpg',
          product: 'TechCrunch',
          scope: 'Global',
          category: 'Business',
          tags: ['Startup', 'Tech'],
          popularity: 80,
          status: '',
          countdown: undefined
     },
     {
          id: 18,
          title: 'JavaOne 2024',
          date: '2024-10-18',
          location: 'Tokyo, Japan',
          description: 'Java’s biggest conference for developers around the world.',
          hashtag: '#JavaOne',
          image: 'https://example.com/images/javaone.jpg',
          product: 'Java',
          scope: 'Global',
          category: 'Tech',
          tags: ['Java', 'Conference'],
          popularity: 84,
          status: '',
          countdown: undefined
     },
     {
          id: 19,
          title: 'Google Analytics Summit 2024',
          date: '2024-09-05',
          location: 'Online',
          description: 'Master Google Analytics with industry leaders.',
          hashtag: '#GoogleAnalytics',
          image: 'https://example.com/images/ga_summit.jpg',
          product: 'Google Analytics',
          scope: 'Global',
          category: 'Analytics',
          tags: ['Google Analytics', 'Summit'],
          popularity: 75,
          status: '',
          countdown: undefined
     },
     {
          id: 20,
          title: 'Cloudflare Connect 2024',
          date: '2024-07-10',
          location: 'Paris, France',
          description: 'Learn about the latest innovations in cloud infrastructure.',
          hashtag: '#CloudflareConnect',
          image: 'https://example.com/images/cloudflare.jpg',
          product: 'Cloudflare',
          scope: 'Regional',
          category: 'Tech',
          tags: ['Cloud', 'Security'],
          popularity: 79,
          status: '',
          countdown: undefined
     }
];
